import { canSend, graphUrl, whatsappConfig } from "./config";

/**
 * The outbound half of the Cloud API: sending a reply, and marking an inbound
 * message as read so the customer sees the blue ticks.
 *
 * Everything that talks to Meta goes through here.
 */

export type SendResult =
  | { ok: true; messageId: string }
  | { ok: false; error: string; retryable: boolean };

type GraphError = {
  error?: { message?: string; type?: string; code?: number; error_subcode?: number };
};

/**
 * Send a free-form text reply.
 *
 * Only valid inside the 24-hour customer service window — outside it Meta
 * rejects the send and only an approved template will go through. The caller
 * checks the window first so the owner gets a clear explanation rather than a
 * raw Graph API error.
 */
export async function sendTextMessage(to: string, body: string): Promise<SendResult> {
  if (!canSend) {
    return { ok: false, error: "WhatsApp is not configured on this deployment.", retryable: false };
  }

  const text = body.trim();
  if (!text) {
    return { ok: false, error: "Refusing to send an empty message.", retryable: false };
  }
  // Meta's hard limit on a text body. Truncating silently would put words in
  // the owner's mouth, so this is an error the inbox shows instead.
  if (text.length > 4096) {
    return {
      ok: false,
      error: `That reply is ${text.length} characters; WhatsApp allows 4096.`,
      retryable: false,
    };
  }

  try {
    const response = await fetch(graphUrl(`${whatsappConfig.phoneNumberId}/messages`), {
      method: "POST",
      headers: {
        Authorization: `Bearer ${whatsappConfig.accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        messaging_product: "whatsapp",
        recipient_type: "individual",
        to,
        type: "text",
        // Link previews off: a preview of a product URL is generated by Meta
        // and we cannot see what it will say.
        text: { preview_url: false, body: text },
      }),
    });

    const payload: unknown = await response.json().catch(() => ({}));

    if (!response.ok) {
      const message =
        (payload as GraphError)?.error?.message ?? `Graph API responded ${response.status}`;
      return {
        ok: false,
        error: message,
        // 5xx and rate limits are worth another go; a 400 means the request
        // itself is wrong and retrying changes nothing.
        retryable: response.status >= 500 || response.status === 429,
      };
    }

    const messageId =
      (payload as { messages?: { id?: string }[] })?.messages?.[0]?.id ?? `sent-${Date.now()}`;

    return { ok: true, messageId };
  } catch (error) {
    console.error("[whatsapp] send failed", error);
    return { ok: false, error: "Could not reach WhatsApp. Try again.", retryable: true };
  }
}

/**
 * Mark an inbound message read. Cosmetic but worth doing — the customer sees
 * that the message landed, which matters when a reply is waiting on the owner.
 * A failure here is logged and swallowed: it must never block a reply.
 */
export async function markAsRead(messageId: string): Promise<void> {
  if (!canSend) return;

  try {
    await fetch(graphUrl(`${whatsappConfig.phoneNumberId}/messages`), {
      method: "POST",
      headers: {
        Authorization: `Bearer ${whatsappConfig.accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        messaging_product: "whatsapp",
        status: "read",
        message_id: messageId,
      }),
    });
  } catch (error) {
    console.error("[whatsapp] could not mark message read", error);
  }
}
